### PR TITLE
additional data

### PR DESCRIPTION
**Pull request by ChaosSaber**
**What I did:**
added type to perks
added exotic flag to weapons/armour

**Why I did it:**
to filter perks for their type and weapons/armour after exotics

### CODE REVIEW

**Comment by atomicptr** [comment]
Hm, instead of having a flag: "exotic" wouldn't it make more sense to add the rarity in general to the item? Because they started sorting them by rarity and name in the game :).

```yaml
# Ragesaber.yml
name: Ragesaber
rarity: Rare # I think?

# TheHunger.yml
name: The Hunger
rarity: Exotic
```

I'm not sure about the "type" flag in perks, do perks have types? As far as I'm aware the type relates to cells and their slots. Does it make sense that Ragesaber has Ragehunter which is Power? The primary reason why I decided to split perks away from cells was (besides being able to easily reuse them in weapons/armor) because I think we will eventually see cells which have more then one perk and in that case the "type" really doesn't make any sense at all anymore. Imagine a cell which gives you dunno: +Ragehunter +Nine Lives, is it Defense? Or maybe Power?

**Comment by ChaosSaber** [comment]
hmm, yeah the rarity seems to make more sense and could be reused for other things. Will change that. What are the rarities?: Common, Uncommon, Rare, Epic and Exotic, or?

Maybe "type" is not the best word for it, but i think it is useful to categorize the skills. At least in my case it makes sense to filter the Perks after their type/category. It makes searching for them easier. And the multi perk cells would need a probably big overhaul of the current system, so i don't think we will see it in the near future. Or i'm already wrong in 2 days. We will see, what the ostian cells are xD

**Comment by atomicptr** [comment]
> What are the rarities?: Common, Uncommon, Rare, Epic and Exotic, or?

Yes

> Maybe "type" is not the best word for it, but i think it is useful to categorize the skills

I think that perks and slot types are unrelated, or else why is Fireblade a thing?

image

That weapon has +2 Rage and no Power slot? Cells have slots though and give you perk bonuses (though only one type right now). 

>  And the multi perk cells would need a probably big overhaul of the current system

Not really, the system is designed right now with that in mind. Or do you mean on their end?

**Comment by ChaosSaber** [comment]
If you look at the [wiki](https://dauntless.gamepedia.com/Perks) for perks, you see that every perk has a type, so i'm at least not the only one who thinks so. But that is a classic clash of opinions.

> I think that perks and slot types are unrelated

yes they are, but each slot type can hold only specific perks which can't be found in other slottypes. So there is a correlation between them. You can also think of the Fireblade as a weapon with 2 power slots, a technique slot and an utility slot, just that the two power slots are preoccupied.

> Not really, the system is designed right now with that in mind. Or do you mean on their end?

i mean on their end.

**Comment by atomicptr** [comment]
Hm.... well, we can add it for now I guess, will at least make it easier to determine icons 🤔. Do you also want to add the rarity thing into this PR? Also would be nice if the location of these attributes would be consistent (I've noticed a few inconsistencies) and above the huger unique_effects, perk etc. lists :).

**Comment by ChaosSaber** [comment]
Yes i would put the rarity into this PR. Will begin with the weapons, for more i will probably don't have time today. Will put it after the tier and before the perks/unique effects.
And moved the type for Knockout King above the key to solve the inconsistence.

**Comment by ChaosSaber** [comment]
rarity added to all armour and weapons

**Pull request merged**
