### PR TITLE
Adding language support for the builder

### PR DESCRIPTION
**Pull request by charlesgael**
**What I did:**
Added support for react-intl with translation files as JSON files in a folder.
Separated "string" data from actual data.
Added French language as well as support for new possible languages

**Mockups, screenshots, evidence:**
image

Build link didn't change from your version to mine, fortunately :)
Added a select field for selecting language (you can change it later on, it's just for conveniance)
Make sure to update a bit either sizes or spacing, because french is taking up more space than english.

### CODE REVIEW

**Comment by atomicptr** [comment]
Is there a specific reason why you've changed the data format of the json? (Case changes) This PR will break every application that is using the data.json right now.

**Comment by atomicptr** [comment]
> Is there a specific reason why you've changed the data format of the json? (Case changes) This PR will break every application that is using the data.json right now.

Dunno if you haven't seen this post, but without an answer/solution to this issue I sadly can't merge this (Even tho I really want to). There are a few apps which use the data set and I really don't want to break them without a good reason.

**Comment by atomicptr** [comment]
I'd really love to merge this, but the issue mentioned above is a huge issue to me. Not even getting an answer and now this is closed? I don't get it :(. I don't want your work to go to waste.

**Comment by charlesgael** [comment]
Hey, can I get you on discord ? Easier to get going

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
