### PR TITLE
Add "Recruit's" to the beginning of "Repeater"

### PR DESCRIPTION
**Pull request by siddagra**
**What I did:**
Add "Recruit's" to the beginning of "Repeater"

**Why I did it:**
I think you may have forgotten to add "Recruit's" to the beginning of the "Repeater" string. I have changed/added this.

**Fixes issue (include link):**
I think you may have forgotten to add "Recruit's" to the beginning of the "Repeater" string. I have changed/added this.

### CODE REVIEW

**Comment by siddagra** [comment]
I mean in names.json

**Comment by atomicptr** [comment]
Sadly this is intentional :). I don't want the old ID to be occupied by something else otherwise this would break the converter code.

You can btw see the Recruits Repeaters sitting at 169 :).

**Comment by siddagra** [comment]
Ok. Thank you

**Comment by siddagra** [comment]
I do not find Recruit's Repeaters at 169 of names.json:

https://raw.githubusercontent.com/siddagra/dauntless-builder/master/.map/names.json

**Comment by atomicptr** [comment]
Your version seems to be very outdated check this: https://www.dauntless-builder.com/map/names.json this has like 195 weapons while yours only features around 100

**Comment by siddagra** [comment]
Thnx a bunch!

**Pull request closed without merging**
